[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "base58>=2.1.1",
    "base58check>=1.0.2",
    "numpy>=2.2.2",
    "pyopencl>=2025.1",
    "python-bitcoinrpc>=1.0",
    "tk>=0.1.0",
]
